version: "3"
services:
  coturn:
    image: docker.io/coturn/coturn:4.6-alpine
    network_mode: "host"
    # These ports need to be opened on the hosts firewall!
    # because this uses the host network
    #   ufw allow 49152:65535/udp
    #   ufw allow 3478/udp
    #   ufw allow 3478/tcp
    #
    tty: true
    environment:
      - TURN_PORT_START=49152
      - TURN_PORT_END=65535
      - TURN_REALM=crashgiants.io
    ports:
      - "3478:3478"
    volumes:
      - ./data/coturn:/etc/coturn

  # generate configs with
  # docker-compose run --rm -e SYNAPSE_SERVER_NAME=my.matrix.host -e SYNAPSE_REPORT_STATS=yes synapse generate
  synapse:
    image: docker.io/matrixdotorg/synapse
    restart: unless-stopped
    environment:
      - SYNAPSE_SERVER_NAME=crashgiants.io
      - SYNAPSE_REPORT_STATS=no
    ports:
      - 8448:8448/tcp
      - 8008:8008/tcp
    volumes:
      - ./data/synapse:/data


  # generate config with
  # docker run --name tmp-nginx-container -d nginx
  # docker cp tmp-nginx-container:/etc/nginx/nginx.conf ./data/nginx/nginx.conf
  # docker rm -f tmp-nginx-container
  nginx:
    image: docker.io/nginx:1.22.1-alpine
    volumes:
      - ./data/nginx:/etc/nginx
    ports:
      - "80:80"
  # db:
  #   image: docker.io/postgres:12-alpine
  #   # Change that password, of course!
  #   environment:
  #     - POSTGRES_USER=synapse
  #     - POSTGRES_PASSWORD=changeme
  #     # ensure the database gets created correctly
  #     # https://matrix-org.github.io/synapse/latest/postgres.html#set-up-database
  #     - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
  #   volumes:
  #     # You may store the database tables in a local folder..
  #     - ./data/schemas:/var/lib/postgresql/data
  #     # .. or store them on some high performance storage for better results
  #     # - /path/to/ssd/storage:/var/lib/postgresql/data
